# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: configdemo
  name: configdemo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: configdemo
  template:
    metadata:
      labels:
        app: configdemo
    spec:
      containers:
        - image: docker.io/keerthi19/configdemo:withapp2
          name: server
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          ports:
            - containerPort: 8082
              name: web
              protocol: TCP
          volumeMounts:
            - name: configvol
              mountPath: "/logs/config"
      volumes:
        - name: configvol
          configMap:
            name: spring-config

---
apiVersion: v1
kind: Service
metadata:
  name: configdemo
spec:
  type: LoadBalancer
  selector:
    app: configdemo
  ports:
  - name: http
    port: 8082
    targetPort: 8082
---       